# Generated by Django 3.2.13 on 2022-05-20 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipelib", "0003_measurement"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
        ),
    ]
