# Generated by Django 3.2.13 on 2022-05-23 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipelib', '0005_item_recipe'),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID'
                    )
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
    ]
