# Generated by Django 3.2.13 on 2022-05-24 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipelib', '0005_item_recipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeMeasurementIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipelib.ingredient')),
                ('measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipelib.measurement')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipelib.recipe')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(through='recipelib.RecipeMeasurementIngredient', to='recipelib.Ingredient'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='measurements',
            field=models.ManyToManyField(through='recipelib.RecipeMeasurementIngredient', to='recipelib.Measurement'),
        ),
    ]
