# Generated by Django 3.2.13 on 2022-05-24 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipelib', '0007_tag_placeholder_url'),
        ('recipelib', '0008_recipe_ingredient_measurement'),
    ]

    operations = [
    ]
