# Generated by Django 3.2.13 on 2022-05-24 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipelib', '0010_recipetag'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(through='recipelib.RecipeTag', to='recipelib.Tag'),
        ),
    ]
