# Generated by Django 3.2.13 on 2022-05-25 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipelib', '0012_alter_item_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture_url',
            field=models.CharField(max_length=300),
        ),
    ]
