# Generated by Django 3.2.13 on 2022-06-12 22:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipelib', '0014_like'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Like',
            new_name='Rating',
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('recipe', 'user')},
        ),
    ]
