# Generated by Django 3.2.13 on 2022-06-12 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipelib', '0015_auto_20220612_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='like',
            field=models.BooleanField(default=True),
        ),
    ]
