# Generated by Django 3.2.13 on 2022-06-19 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipelib', '0017_follower'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(blank=True, null=True, related_name='followers', to='recipelib.Profile'),
        ),
    ]
