# Generated by Django 3.2.13 on 2022-06-19 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipelib', '0019_alter_profile_following'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follower',
        ),
    ]
