name: Django CI

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]

jobs:
  deploy:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Build docker image
      run: docker-compose up -d
    - name: Run Tests
      run: docker-compose run web python manage.py test